---
# tasks file for datashield-opal-setup
- name: Opal Installation
  block:
    - name: Opal - Get Opal Key
      become: true
      become_user: "{{ Host_User_Name }}"
      shell: curl -fsSL https://www.obiba.org/assets/obiba-pub.pem | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/obiba.gpg
      register: opal_obiba_output
    - name: Opal - Tee Opal
      become: true
      become_user: "{{ Host_User_Name }}"
      shell: echo 'deb https://obiba.jfrog.io/artifactory/debian-local all main' | sudo tee /etc/apt/sources.list.d/obiba.list
      register: opal_tee_output
    - name: Opal - Update apt packages
      become: true
      become_user: "{{ Host_User_Name }}"
      apt:
        update_cache: yes
    - name: Opal - Installing Opal
      become: true
      become_user: "{{ Host_User_Name }}"
      apt:
        name: opal

- name: Opal Configuration
  block:

  - name: Set Java Version
    become: true
    become_user: "{{ Host_User_Name }}"
    lineinfile:
      path: /etc/default/opal
      search_string: 'JAVA='
      line: "JAVA=/usr/bin/java"
      #line: "JAVA=/opt/java/jdk8u402-b06/bin/java"
      # TODO: replace w/ ${JAVA_HOME}
      # 11.0.22+7

  - name: Run shiro-hasher
    become: true
    become_user: "{{ Host_User_Name }}"
    expect:
      command: "./shiro-hasher -p"
      responses:
        "(.*)Password(.*)": "{{ opal_administrator_password }}"
      chdir: "/usr/share/opal/tools/"
      echo: true
    register: shiro_hasher_result

  # Debugging  

  - name: Display shiro-hasher output
    debug:
      var: shiro_hasher_result.stdout_lines[2]

  - name: Display intended password
    debug:
      var: opal_administrator_password

  - name: Opal - Update Admin Password 
    become: true
    become_user: "{{ Host_User_Name }}"
    lineinfile:
      path: /etc/opal/shiro.ini
      search_string: ',admin' # line: "admin = {{shiro_hasher_result.stdout_lines[2]}},admin"
      line: "{{opal_administrator_username}}={{shiro_hasher_result.stdout_lines[2]}},admin" # Reset to default
      
  - name: Opal - Configure Port (HTTP)
    become: true
    become_user: "{{ Host_User_Name }}"
    lineinfile:
      path: /etc/opal/opal-config.properties
      search_string: 'org.obiba.opal.http.port'
      line: "org.obiba.opal.http.port={{opalHTTPport}}"

  - name: Opal - Configure Port (HTTPS)
    become: true
    become_user: "{{ Host_User_Name }}"
    lineinfile:
      path: /etc/opal/opal-config.properties
      search_string: 'org.obiba.opal.https.port'
      line: "org.obiba.opal.https.port={{opalHTTPSport}}"

  - name: Opal - Restarting Opal to Update Configuration
    become: true
    become_user: "{{ Host_User_Name }}"
    systemd:
      name: opal
      state: restarted
  - name: Opal - pause for Opal restart 
    pause:
      seconds: "{{ pause_seconds|default(10) }}"
  - name: Opal - Check Opal is running correctly
    become: true
    become_user: "{{ Host_User_Name }}"
    systemd:
      name: opal
      state: started