---
# tasks file for getinfo
- name: Checking System Information
  debug:
    msg: "The hostname is {{ ansible_distribution }}, version: {{ ansible_facts['lsb']['release'] }}."

- name: Gathering Package Facts
  package_facts:
    manager: auto

- name: apt - Update cache
  become: true
  become_user: "{{ Host_User_Name }}"
  apt:
    update_cache: yes

- name: Install unzip package
  become: true
  become_user: "{{ Host_User_Name }}"
  apt:
    name: zip

# Install Gdebi
- name: Install gdebi-core
  become: true
  become_user: "{{ Host_User_Name }}"
  apt:
    name: gdebi-core
    state: present

# Install Java
- name: Install Java (8)
  become: true
  become_user: "{{ Host_User_Name }}"
  apt:
    name: openjdk-8-jdk
    state: present