---
# tasks file for getinfo
- name: Checking System Information
  debug:
    msg: "The hostname is {{ ansible_distribution }}, version: {{ ansible_facts['lsb']['release'] }}."

- name: Gathering Package Facts
  package_facts:
    manager: auto

# Install Gdebi
- name: Install gdebi-core
  become: true
  apt:
    name: gdebi-core
    state: present