---
- hosts: DSservers

  # Pre-Roles Tasks
  # pre_tasks:

  # Roles
  roles:

    # Custom
    - role: datashield-getinfo

    # From Galaxy
    #- role: gantsign.java
      #java_version: '8.0.402+6' #Java 8
      #java_version: '11.0.22' # Java 11
    - role: kwoodson.yedit
   
    # Custom
    - role: datashield-mongodb-setup
    - role: datashield-R-setup
    - role: datashield-opal-setup
    - role: datashield-rock-setup
    - role: datashield-opal-python-api-setup

  # Tasks
  # tasks: