name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Prepare Ansible configuration for testing
      run: make

    #- name: Run check
    #  run: make check

    #- name: Run distcheck
    #  run: make distcheck
